name = "livetrackings1"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

[[d1_databases]]
binding = "DB"
database_name = "livetrackings-db"
database_id = ""

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*.ts"]

[build.upload]
format = "service-worker"

[env.production.build]
command = "npm run build:prod"
